# Generated by Django 2.1.4 on 2019-03-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.AlterField(
            model_name='product',
            name='base_price',
            field=models.IntegerField(verbose_name='قیمت پایه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='customer_price',
            field=models.IntegerField(verbose_name='قیمت مصرف\u200cکننده'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=1000, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=200, verbose_name='شرح کالا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off_cash_percent',
            field=models.IntegerField(verbose_name='درصد تخفیف نقدی'),
        ),
    ]
